services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "8000:80"
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  php:
    build:
      context: api/
    volumes:
      - ./api/:/var/www/html
    environment:
      - APP_ENV=dev
    container_name: api_php

  database:
    image: mysql:8.0
    volumes:
      - ./api/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fabio_code_academy
