services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "8000:80"
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    container_name: fabio_code_academy_nginx

  php:
    build:
      context: api/
    volumes:
      - ./api/:/var/www/html
    environment:
      - APP_ENV=dev
    container_name: fabio_code_academy_api

  database:
    image: mysql:8.0
    volumes:
      - ./api/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fabio_code_academy
    container_name: fabio_code_academy_mysql
  
  frontend:
    build:
      context: frontend/
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    container_name: fabio_code_academy_frontend