version: '3'

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - ./api:/var/www/html
    environment:
      - APP_ENV=dev

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fabio_code_academy

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
